### ISSUE TITLE
Removed from Chrome Webstore?

### ISSUE THREAD

**Issue by JZubero** [aniketkudale/inspect-devices#1]
The link in the README is leading to a 404 page: https://chrome.google.com/webstore/detail/inspect-devices/gekjjfijolflhgbhjggpflnklibhkmjh

Chrome auto-deactivated the extension with the following message:

> Diese Erweiterung verletzt die Chrome Web Store-Richtlinien.

(This extension violates the Chrome Web Store guidelines.)

**Comment by aniketkudale** [comment]
Yes need to update extension permissions, will be available back again in next 2-3 days.

**Comment by aniketkudale** [comment]
@JZubero Try this https://chrome.google.com/webstore/detail/inspect-devices/kmhbjbgkpaceeioiadjkfinjbckgckim

**Comment by JZubero** [comment]
@aniketkudale Works! Thanks a lot :+1:
